sudo: false

language: python
python:
  - "3.5"
  - "3.6"

install: pip install tox-travis
script: tox

cache: pip

matrix:
  fast_finish: true

notifications:
    #webhooks:
    #    urls:
    #        - https://webhooks.gitter.im/e/4792e76205b696e243ff
    #    on_success: change  # options: [always|never|change] default: always
    #    on_failure: always  # options: [always|never|change] default: always
    #    on_start: never     # options: [always|never|change] default: always

